### ISSUE TITLE
Malformed cab file generated

### ISSUE THREAD

**Issue by ptr0x1** [Keramas/CabCloningFactory#1]
Hey, I came across this repository during my research as I'm working on a really similar test as yours. The tool still works and rips the generated cert out and pastes it onto the new cab file but the final forged cab file is malformed and cannot be opened.

I assume it has to be something in the header calculation but I was wondering if you ran into that before and maybe know where I can start looking? 

I found the sls cab file that you used for testing and it worked with that just fine, but I can't seem to use it with cab files that have been signed by a different body.

Thanks in advance!

**Comment by ptr0x1** [comment]
As an update looks like it was the number of files byte in the header that was malformed and fixing it allowed the cabinet to open. However I am still unclear on the end result of the tool. Can this truly bypass the signature check, or will it add the original signature but the hash will mismatch, resulting in an overall untrusted certificate?

There is very limited information on CAB files so it's hard to verify if this has since been fixed by Microsoft or not.

**Comment by Keramas** [comment]
Hello @ptr0x1 ! It has been a super long time since I looked at cabs and even this repo, but nice to see someone else is researching this too. 

In terms of your question I will provide a bit of background: This was essentially researched and created due to a development oversight that mis-implemented a security check. Instead of actually fully validating the signature, it was only looking to make sure that 1. there was a signature (valid or not), and 2. that the signature had a specific CN associated it with. With that said, it will not bypass correct coding practices that aim to validate the signature completely, but in cases where you just need to spoof a signature onto a cab that matches the target CN (or other data), then it should get passed that. So there is no issues with Microsoft, this is just specific to some bad coding practices and developers mis-steps.

It is a little wonky and there are some quirks and nuances with all the offsets for different cab compression methods, but with a little trial and error it will likely copy over and work properly.

**Comment by ptr0x1** [comment]
Absolutely, thanks a lot for your explanation! I noticed it was a while ago but I was hoping you still remember something :) 

This was super helpful, I suspected this is how validation looked in your case. I could verify that during my test the proper authenticode verification takes place and not just CN matching using your tool. CABs are really interesting and have had relatively little limelight yet.
